j29.admin.login:
  resource: '@J29Bundle/Controller/admin/SecurityController.php'
  type: annotation

j29.admin.logout:
  path: '/logout'

j29.admin:
  resource: '@J29Bundle/Controller/admin'
  type: annotation
  
j29.category:
 resource: '@J29Bundle/Controller/category'
 type: annotation

j29.crud:
  resource: '@J29Bundle/Controller/crud'
  type: annotation

j29.www:
  resource: '@J29Bundle/Controller/www'
  type: annotation