services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  
  J29Bundle\:
    resource: '../../src/J29Bundle/*'
    exclude: '../../src/J29Bundle/Entity'

  #---------- JLibrary ----------#

  JLibrary\Service\Sanitizer:
    public: true
  
  JLibrary\Service\ManageCurrentlyUsed:
    public: true
  
  JLibrary\Service\SingleFileManager:
    arguments: [%upload_directories%]
    public: true