parameters:
    locale: en
    site_organization: 'ORGANIZATION'
    base_image_directory: '%kernel.root_dir%/../public_html/images/'
    base_upload_directory: '%kernel.root_dir%/../public_html/uploads/'
    
    # Upload Directories
    upload_directories:
        board_members: '%kernel.root_dir%/../public_html/uploads/board_members/'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }

# Twig Configuration
twig:
    globals:
        page_title_suffix: '%site_organization%'
        global_stylesheet: 'dist/j29-styles.css'
        global_javascript: 'dist/j29-scripts.js'
