security:
    providers:
        in_memory:
            memory:
                users:
                    THE_USERNAME:
                        password: bcryptpassword
                        roles: 'ROLE_SUPER_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: NAMESPACE.admin.login
                check_path: NAMESPACE.admin.login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: NAMESPACE.admin.logout
                target: NAMESPACE.frontend.homepage

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]